cabal-version:      3.0
name:               code
version:            0.1.0.0
build-type:         Simple

common warnings
  ghc-options: -Wno-x-partial

library
  import:           warnings
  exposed-modules:
    Algorithms
    FFT
    LinearAlgebra
    NumberTheory
    Queue
    Rational
    SymbolicDifferentiation
    Polynomial
  build-depends:    base ^>=4.20.2.0
  hs-source-dirs:   src
  default-language: GHC2024
  default-extensions:
    CPP
  cpp-options:
    -UTEMPLATE

