cabal-version:      3.0
name:               code
version:            0.1.0.0
build-type:         Simple

common base
  ghc-options: -Wno-x-partial
  build-depends:
    , base ^>=4.20.2.0
    , containers ^>= 0.8
    , mtl
  default-language: GHC2024
  default-extensions:
    CPP

flag dev
  default: False

library
  import:           base
  exposed-modules:
    Playground.Algorithms
    Playground.FFT
    Playground.Foldable
    Playground.LinearAlgebra
    Playground.NumberTheory
    Playground.Queue
    Playground.Rational
    Playground.Language.RegExp
    Playground.Language.FA
    Playground.Search
    Playground.SearchTree
    Playground.SymbolicDifferentiation
    Playground.Polynomial
  hs-source-dirs:   src
  default-language: GHC2024
  if flag(dev)
    cpp-options:
      -UTEMPLATE
  else
    cpp-options:
      -DTEMPLATE


test-suite test
  import:           base
  default-extensions:
    TemplateHaskell
  type:             exitcode-stdio-1.0
  main-is:          Spec.hs
  hs-source-dirs:   test
  build-depends:
    , code
    , QuickCheck
    , hspec ==2.*
  build-tool-depends: hspec-discover:hspec-discover == 2.*
  other-modules:
    Playground.Test.SearchTreeSpec
    Playground.Test.Language.RegExpSpec
  if flag(dev)
    cpp-options:
      -UTEMPLATE
  else
    cpp-options:
      -DTEMPLATE

